### ISSUE TITLE
The WMI service or the WMI provi der returned an unknown error: HRESULT 0x800706be 

### ISSUE THREAD

**Issue by ivugrinec** [lahell/PSDiscoveryProtocol#11]
Hi, i have been using your tool! It works great for most of Windows 10 domain computers. 

 i have an issue with two computers on a network. This is the error: 

![image](https://user-images.githubusercontent.com/38259498/104749962-b5dd1880-5753-11eb-8c30-21667086c616.png)
Any idea what my be wrong? Any advice how to debug?

**Comment by lahell** [comment]
Sorry for the very late reply. I have never seen this error before. Based on a few quick searches, the error 0x800706be could be caused by problems with RPC. I would look for events related to RPC and DCOM in Event Viewer.

**Comment by lahell** [comment]
@ivugrinec, have you tried `Invoke-DiscoveryProtocolCapture -Type CDP -Force`?

**Comment by lahell** [comment]
Closing this as I can't reproduce it and more than a year has gone by without an answer to my last question.
