### ISSUE TITLE
Ability to display NIC Port

### ISSUE THREAD

**Issue by jaromirk** [lahell/PSDiscoveryProtocol#16]
Hello, thank you for this awesome project!

Would it be possible to add information what pNIC is connected to where? Assuming I have multiple NICs connected to different switches/switch ports.

THX!

**Comment by jaromirk** [comment]
Well, this is PERFECT!!! Thank you! It's exactly what I was looking for!!! I love it, I can now see both NICs connected to switch - so I can validate if it's symmetric.
![image](https://user-images.githubusercontent.com/9829838/134531873-9f0cffec-82d8-4d98-9039-15ddf322b2cd.png)

**Comment by jaromirk** [comment]
btw. I guess you cannot get info from switch about what are allowed VLANs, right?

**Comment by lahell** [comment]
@jaromirk Thanks for testing, feedback and screenshot. Also, thank you for opening this issue. When I wrote this module my focus was on Windows 10 clients. Your use case never even crossed my mind.

I don't think I have seen info about allowed VLANs in any LLDP packet before. You can export to pcap and have a closer look in Wireshark: `'COMPUTER1', 'COMPUTER2' | Invoke-DiscoveryProtocolCapture | Export-Pcap -Path packets.pcap -Invoke`

If you don't want to install Wireshark you can at least get a list of TLVs and raw data using `Get-DiscoveryProtocolData -Verbose`.
