### ISSUE TITLE
Limit of Single Device per LLDP Discovery

### ISSUE THREAD

**Issue by avlec** [lahell/PSDiscoveryProtocol#20]
The tool doesn't seem to provide support for multiple LLDP packets being recivied on the same interface. I have a ethernet interface that is connected to a switch. I can see in wireshark that 2 LLDP messages are being recieved, one for a managed switch and one for a device on a unmanaged switch that sits between the computer and the managed switch see below for an illustration of the layout. What I end up seeing is just device on that ethernet interface, I do notice that the LLDP message for device arrives before managed sw.

```
[ computer ] - - - - -\
                [unmanaged sw] - - - - - [managed sw]
[ device ] - - - - - -/
```

**Comment by lahell** [comment]
What is the destination MAC address for the two LLDP packets you see in Wireshark?

**Comment by avlec** [comment]
01-80-c2-00-00-0e
Note: device can see both computer and managed switch

**Comment by lahell** [comment]
Sorry for the late reply. It is correct that only the first packet will be displayed. That was a design choice. I think none of the packets should be able to reach your computer. If the unmanaged switch conform to standards it should discard both packets, unless it is actually a hub.
