### ISSUE TITLE
Doesn't work with Teamed interfaces. 

### ISSUE THREAD

**Issue by GMB23** [lahell/PSDiscoveryProtocol#22]
Doesn't work with Teamed interfaces. Any way to get it to work with a teamed interface?

**Comment by lahell** [comment]
I don't have any way of testing any time soon, but you could try to remove `-Physical` from [this](https://github.com/lahell/PSDiscoveryProtocol/blob/3776f5814a09b2ae90357868625330b386d86c1f/PSDiscoveryProtocol/PSDiscoveryProtocol.psm1#L269) line.

**Comment by lahell** [comment]
Did you have any luck with this, @GMB23?

**Comment by GMB23** [comment]
Yes. There were a couple “-physical” flags that I took out, and then it worked. Thanks

Sent from my iPhone

On Jan 25, 2023, at 10:40 AM, lahell ***@***.***> wrote:

﻿

Did you have any luck with this, @GMB23<https://github.com/GMB23>?

**Comment by lahell** [comment]
@GMB23 Thanks for testing. You removed `-Physical` from [line 269](https://github.com/lahell/PSDiscoveryProtocol/blob/3776f5814a09b2ae90357868625330b386d86c1f/PSDiscoveryProtocol/PSDiscoveryProtocol.psm1#L269) and [line 360](https://github.com/lahell/PSDiscoveryProtocol/blob/3776f5814a09b2ae90357868625330b386d86c1f/PSDiscoveryProtocol/PSDiscoveryProtocol.psm1#L360) but did not change `CaptureType = 'Physical'` on [line 309](https://github.com/lahell/PSDiscoveryProtocol/blob/3776f5814a09b2ae90357868625330b386d86c1f/PSDiscoveryProtocol/PSDiscoveryProtocol.psm1#L309)?
