### ISSUE TITLE
DCBX LLDP messages

### ISSUE THREAD

**Issue by jaromirk** [lahell/PSDiscoveryProtocol#24]
Hello,

it's more a feature request than a issue. I did capture LLDP packets and did not see DCBX LLDP messages. Would it be possible to capture it too?

This is output from my switch where I can see messages were transmitted.

![image](https://user-images.githubusercontent.com/9829838/225868282-9b7a3967-c86f-4895-89c9-a2d0ae2aa51f.png)

Here is some info I found about it https://www.juniper.net/documentation/us/en/software/junos/traffic-mgmt-qfx/topics/concept/fibre-channel-dcbx-understanding.html

**Comment by jaromirk** [comment]
hmm, weird. regarding this it looks like it should have been captured with your posh Module https://enterprise-support.nvidia.com/s/article/lldp-dcbx-packet-format-examples-ieee-and-cee--wireshark-x#jive_content_id_LLDP_DCBX__CEE_Mode

**Comment by lahell** [comment]
@jaromirk 
Quote from README.md:
> PSDiscoveryProtocol does not return all information available in CDP and LLDP packets. If you want to know what information is available use Export-Pcap and open the pcap file in Wireshark or another tool with a more complete implementation.

You can also use `Invoke-DiscoveryProtocolCapture -Type LLDP | Get-DiscoveryProtocolData -Verbose`. You will get a list of TLVs. DCBX TLVs will probably have OUI : 00-1B-21. The raw data is presented as hex and ascii, but I would have to find the DCBX specification in order to read it correctly.

What info do you need from DCBX? 

I don't think I have any devices capable of sending DCBX. Would you mind sending a base64 encoded packet to me using the [Contact Owners form at PowerShell Gallery](https://www.powershellgallery.com/packages/PSDiscoveryProtocol/1.4.2/ContactOwners)? Get the base64 string using the following code.

```
$Packet = Invoke-DiscoveryProtocolCapture -Type LLDP
[Convert]::ToBase64String($Packet.Fragment)
```

**Comment by jaromirk** [comment]
looks like switch is not sending it. I want to check switch configuration - as I can check PFC/ETS configuration this way for RDMA Network adapters.

![image](https://user-images.githubusercontent.com/9829838/225974310-24db980e-08e8-4278-a826-e58d6f966b7a.png)

**Comment by jaromirk** [comment]
THis is how it should look like if you have ETS/PFC info in packet. 
https://enterprise-support.nvidia.com/s/article/lldp-dcbx-packet-format-examples-ieee-and-cee--wireshark-x#jive_content_id_LLDP_DCBX__CEE_Mode

I'll try to figure out how to convince switch to send the info.

**Comment by jaromirk** [comment]
Just leaving DCBX specs here... https://www.ieee802.org/1/files/public/docs2008/az-wadekar-dcbx-capability-exchange-discovery-protocol-1108-v1.01.pdf ... I hope I will be able to capture something so we will be able to update your posh module :). It would be great improvement!

**Comment by lahell** [comment]
Thanks for the specs. Is this what you need? [dcbx tlv-select](https://www.dell.com/support/manuals/no-no/smartfabric-os10-emp-partner/smartfabric-os-user-guide-10-5-4/dcbx-tlv-select?guid=guid-44d5a67d-2b42-4582-a32c-5106f59793bd&lang=en-us)

**Comment by jaromirk** [comment]
yeah, but it looks like it's enabled. I opened case with our engineering on what's going on. Either switch is not sending it, or we will need to add another multicast address (which is weird, because it should be LLDP)

**Comment by jaromirk** [comment]
Yes! it needs to be set manually to cee or ieee. Could you take a look into it? It would be great to have it in the output (PFC/ETS config for both iee and cee)

[cee.pcap.txt](https://github.com/lahell/PSDiscoveryProtocol/files/11004458/cee.pcap.txt)
[ieee.pcap.txt](https://github.com/lahell/PSDiscoveryProtocol/files/11004459/ieee.pcap.txt)

**Comment by lahell** [comment]
Do you have an example of what you think the output should look like?

**Comment by jaromirk** [comment]
This is what it looks like inside OS when you configure NICs. Get-NetAdapterQoS
![image](https://user-images.githubusercontent.com/9829838/227476974-14506c2b-180e-46bf-9734-0f1ddda29606.png)

**Comment by jaromirk** [comment]
![image](https://user-images.githubusercontent.com/9829838/227478246-e39378be-5115-42de-a196-6c721273f3ae.png)

**Comment by jaromirk** [comment]
![image](https://user-images.githubusercontent.com/9829838/227478532-fa048206-bb5c-40b8-800b-8a7b4d0d2e93.png)

**Comment by jaromirk** [comment]
What I would love to see is if the configuration on switch is CEE or IEEE. And following information:

**Comment by jaromirk** [comment]
ETS: what priorities were configured and what bandwidth was configured:
![image](https://user-images.githubusercontent.com/9829838/227481706-6fcbb8bc-6c83-4a6b-a44d-42a8e2834856.png)

**Comment by jaromirk** [comment]
And PFC configuration
![image](https://user-images.githubusercontent.com/9829838/227482174-ee7caf58-5e6c-4028-aa40-c48ad97b4b67.png)

**Comment by jaromirk** [comment]
Also PFC itself if it's enabled and if willing is enabled 
![image](https://user-images.githubusercontent.com/9829838/227482780-492e8114-d6a5-47f1-b9ca-d2afd243d077.png)

**Comment by lahell** [comment]
I have created the new branch [feature-dcbx](https://github.com/lahell/PSDiscoveryProtocol/tree/feature-dcbx). Would you mind playing around with different settings and values to make sure it works correctly?

**Comment by lahell** [comment]
Example for testing:
```
$Output = Invoke-DiscoveryProtocolCapture -Type LLDP | Get-DiscoveryProtocolData
$Output.DCBX.IEEE.ETS.BandwidthAssignmentTable
$Output | ConvertTo-Json -Depth 4
```

**Comment by lahell** [comment]
@jaromirk, did you get a chance to test the new branch?

**Comment by jaromirk** [comment]
I'll take a look! Thank you!

**Comment by jaromirk** [comment]
Looks awesome! Just tried IEEE. Will reconfigure switch on monday and try CEE. THank you!!!! 
![image](https://user-images.githubusercontent.com/9829838/229193256-daf1ceac-c568-4a24-8822-7d27d762a9c3.png)

**Comment by jaromirk** [comment]
It's pretty awesome! May I also ask you for this info? 
![image](https://user-images.githubusercontent.com/9829838/229494596-c347ece4-9f38-4d61-855c-1b87ee95a42e.png)

**Comment by lahell** [comment]
It should be there. Pipe `Get-DiscoveryProtocolData` to `ConvertTo-Json -Depth 4` to easily see what is available. 

The following code works for me.
```
$PCAP = (Invoke-WebRequest https://github.com/lahell/PSDiscoveryProtocol/files/11004458/cee.pcap.txt -UseBasicParsing).Content
$Bytes = $PCAP.ToCharArray() -as [byte[]] | Select-Object -Skip 40
$LLDP = ConvertFrom-LLDPPacket -Packet $Bytes
$LLDP.DCBX.CEE.ETS.BandwidthAssignmentTable | Format-Table

$PCAP = (Invoke-WebRequest https://github.com/lahell/PSDiscoveryProtocol/files/11004459/ieee.pcap.txt -UseBasicParsing).Content
$Bytes = $PCAP.ToCharArray() -as [byte[]] | Select-Object -Skip 40
$LLDP = ConvertFrom-LLDPPacket -Packet $Bytes
$LLDP.DCBX.IEEE.ETS.BandwidthAssignmentTable | Format-Table
```

**Comment by jaromirk** [comment]
It is! Super awesome! Thank you! I'll update examples here: https://github.com/DellGEOS/AzureStackHOLs/tree/main/admin-guides/05-NetworkConfiguration#advanced-lldp-information-dcbx THX a million!

**Comment by lahell** [comment]
@jaromirk
Thanks for testing. Did you also test different settings and values on your switch config to make sure my module return the correct values?

**Comment by jaromirk** [comment]
I did test just ieee. Let me reconfigure it to cee

**Comment by jaromirk** [comment]
this is ieee 
![image](https://user-images.githubusercontent.com/9829838/231212810-66c074c4-0de9-4ce4-adf4-c9e5e0f2da03.png)

**Comment by jaromirk** [comment]
gosh, I'm not able to see any dcbx packets if I configure cee - but it's not your fault, switch does not send anything. I assume it's working :). Feel free to release!

**Comment by jaromirk** [comment]
ok, CEE is also fine
![image](https://user-images.githubusercontent.com/9829838/231288090-3085c015-ed0d-4cad-9063-6ba94e4001fa.png)
